
// Generated by https://quicktype.io

import { Cast } from "./Cast";
import { Genre } from "./Genre";
import { Trailer } from "./Trailer";

export interface Movie {
    id:               number;
    title:            string;
    overview:         string;
    tagline:          string;
    budget:           number;
    revenue:          number;
    imdbUrl:          string;
    tmdbUrl:          string;
    posterUrl:        string;
    backdropUrl:      string;
    originalLanguage: null;
    releaseDate:      string;
    runTime:          number;
    price:            number;
    rating:           number;
    genres:           Genre[];
    trailers:         Trailer[];
    casts:            Cast[];
}


